# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
